# Generated by Django 4.1 on 2024-10-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_lending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='borrowed_on',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='lending',
            name='returned',
        ),
        migrations.AddField(
            model_name='lending',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
