# Generated by Django 4.1 on 2024-10-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_borrowed_on_lending_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='lending',
            name='start_date',
        ),
    ]
